### ISSUE TITLE
Compute optimal schedule feature

### ISSUE THREAD

**Issue by tdaron** [ADE-Scheduler/ADE-Scheduler#1057]
Hi !

Since the website is hosted on monhoraire.uclouvain.be the compute feature is missing, is it planned to put it back in ? It was really game changing :)

**Comment by Hokkaydo** [comment]
I totally agree 👍

**Comment by jeertmans** [comment]
Hey! Happy to see this feature was useful :)

It removed for mainly two reasons:
1. Since the latest changes in the EPL bac, people do not have as many choices we had originally, so having a program automatically choose a schedule for you.
2. The EPL is one of the only faculty to really offer a choice, especially in bac. In fact, most faculties impose a given schedule. And some people from the secretary of other faculties disliked to possibility that student may think they have the choice to choose a specific schedule for a TP, when they cannot.

However, I still think some people may enjoy this feature, and it is sad to have it remove (we knew it when accepting to make it the official app).
This may change, like ~ 2 years ago when some faculties didn’t want to promote this tool, but nothing can be guaranteed.

First thing is that we want to keep this GitHub active, and make sure it matches to website in production (which currently isn’t the case).

**Comment by tdaron** [comment]
understood, thanks for the fast answer !

(just putting a little suggestion here but would it be possible when hovering a particular tp/cm to see it's "id" cause yesterday I found myself randomly checking and unchecking checkbox to only select the TP I wanted to see ahah) because some courses (LEPL1373 👀) have a lot of em

**Comment by jeertmans** [comment]
I think it reminds me of something and, as far as I remember, we cannot really fine-tune what is displayed when hovering because the calendar is handled by a third-party library, FullCalendar, and they did not allow use to display the exact information we wanted to have. But maybe I am wrong 🤷🏼‍♂️

**Comment by tdaron** [comment]
Oh ok, at least I already did my schedule I don't have to do it again ahah 

Thanks
