### ISSUE TITLE
Desynchronized classes

### ISSUE THREAD

**Issue by SachaDef** [ADE-Scheduler/ADE-Scheduler#317]
**Describe the bug**
When overviewing the different possible hours to attend to for a class when building an optimal schedule, you do not get the same availabilities whether you click on the class in your week schedule at the center of the screen or on the class in the list at the top-left corner. Some of those desynchronized hours thus are not visible on your schedule.

**To Reproduce**
1. Create a new schedule and add the 'FSA12BA' group of classes (class concerned : 'LEPL1106')
2. Click on the LEPL1106 class on your week schedule at the center and view the different options available for you to choose from; view the same options by clicking on the class in the top-right list (here by clicking on the 'FSA12BA' group and scrolling to the class), there are in this case way less options (namely no options for any TP)
3. The TP's that are available with only one of the two methods are visible nowhere on the schedule, even if they are checked.

**Expected behavior**
Have the same available options with both methods, and have those options appear on the schedule when checked.

**Screenshots of the issue**
![img1](https://user-images.githubusercontent.com/65407167/105341500-77c27780-5bdf-11eb-8e82-d8a36237e14e.png)
![img2](https://user-images.githubusercontent.com/65407167/105341822-d982e180-5bdf-11eb-82e8-2a1a031b6ad7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Famille)
 - Browser: OperaGX
 - Version: LVL2 (core: 72.0.3815.473)

**Smartphone (please complete the following information):**
Not tested

**Additional context**

**Comment by SnaKyEyeS** [comment]
Interesting bug, thanks for the report !
@jeertmans I trust you are the one who should have the better idea where it comes from ?

**Comment by jeertmans** [comment]
Hello @SachaDef, after digging a little bit into the problem, it seems that it comes from a mistake made by the people who encoded this program. As you can see on the official website, TPs are not included neither... As we get all the data from the same source, if they do encoding mistakes, we cannot do
![DeepinScreenshot_select-area_20210121222607](https://user-images.githubusercontent.com/27275099/105414464-d1569080-5c37-11eb-9892-1b797407b25b.png)
 much about this.

Nonetheless, we will try to reach the faculty so that they can fix this.

We could bypass this problem by forcing to fetch all events from all courses but it don't know if this is very smart. We should see if this problem occurs really often.
